### ISSUE TITLE
Panic in plugin leads to multiple `signal: killed` in output

### ISSUE THREAD

**Issue by mfridman** [bufbuild/protoplugin#6]
I threw a `panic` in the plugin handler to see how protoplugin would handle it, and noticed an excessive concatenation of kill signals?

> Failure: plugin custom-plugin: exit status 2; signal: killed; signal: killed; signal: killed; signal: killed; signal: killed; signal: killed; signal: killed

Not sure if this is intended or if we want to fix it. But ideally, it would only display one "signal: killed".

> Failure: plugin custom-plugin: exit status 2; signal: killed

**Comment by bufdev** [comment]
This is likely a `buf` issue and not a `protoplugin` issue - does the same thing happen if you invoke it with `protoc`? `buf` is doing calls in parallel, so it's likely running multiple instances of your plugin.

**Comment by mfridman** [comment]
Yes, you're absolutely right.
